version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes: 
      - api:/usr/src/app/
    depends_on:
      - db
    networks:
      - event-log

  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - event-log

volumes:
  api:
  db:

networks:
  event-log:
    driver: bridge
